//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    Eq,
    DeriveEntityModel,
    Serialize,
    Deserialize,
    facet :: Facet,
    specta :: Type,
    utoipa :: ToSchema,
    utoipa :: ToResponse,
)]
#[sea_orm(table_name = "assignments")]
# [schema (as = Assignments)]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub due: Option<DateTime>,
    pub lock_at: Option<DateTime>,
    pub lock_until: Option<DateTime>,
    pub max_score: Option<i32>,
    pub is_quiz: Option<bool>,
    pub course_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(has_many = "super::submissions::Entity")]
    Submissions,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submissions.def()
    }
}
