//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    Eq,
    DeriveEntityModel,
    Serialize,
    Deserialize,
    facet :: Facet,
    specta :: Type,
    utoipa :: ToSchema,
    utoipa :: ToResponse,
)]
#[sea_orm(table_name = "courses")]
# [schema (as = Courses)]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub code: String,
    pub description: Option<String>,
    pub storage_quota_bytes: Option<i64>,
    pub owner: i32,
    pub home_page: i32,
    pub syllabus_page: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assignments::Entity")]
    Assignments,
    #[sea_orm(
        belongs_to = "super::course_pages::Entity",
        from = "Column::HomePage",
        to = "super::course_pages::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    CoursePages2,
    #[sea_orm(
        belongs_to = "super::course_pages::Entity",
        from = "Column::SyllabusPage",
        to = "super::course_pages::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    CoursePages1,
    #[sea_orm(has_many = "super::enrollments::Entity")]
    Enrollments,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Owner",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assignments.def()
    }
}

impl Related<super::enrollments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Enrollments.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
