//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::assignments::Entity as Assignments;
pub use super::course_pages::Entity as CoursePages;
pub use super::courses::Entity as Courses;
pub use super::enrollments::Entity as Enrollments;
pub use super::submissions::Entity as Submissions;
pub use super::users::Entity as Users;
